// Generated by Xata Codegen 0.28.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  { name: "Categories", columns: [{ name: "Categories", type: "text" }] },
  { name: "GeneralAds", columns: [] },
  { name: "Properties", columns: [] },
  { name: "Vehicles", columns: [{ name: "Subcategory", type: "text" }] },
  { name: "Community", columns: [] },
  { name: "Services", columns: [] },
  { name: "Jobs", columns: [] },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Categories = InferredTypes["Categories"];
export type CategoriesRecord = Categories & XataRecord;

export type GeneralAds = InferredTypes["GeneralAds"];
export type GeneralAdsRecord = GeneralAds & XataRecord;

export type Properties = InferredTypes["Properties"];
export type PropertiesRecord = Properties & XataRecord;

export type Vehicles = InferredTypes["Vehicles"];
export type VehiclesRecord = Vehicles & XataRecord;

export type Community = InferredTypes["Community"];
export type CommunityRecord = Community & XataRecord;

export type Services = InferredTypes["Services"];
export type ServicesRecord = Services & XataRecord;

export type Jobs = InferredTypes["Jobs"];
export type JobsRecord = Jobs & XataRecord;

export type DatabaseSchema = {
  Categories: CategoriesRecord;
  GeneralAds: GeneralAdsRecord;
  Properties: PropertiesRecord;
  Vehicles: VehiclesRecord;
  Community: CommunityRecord;
  Services: ServicesRecord;
  Jobs: JobsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://oly-001-sgstp3.eu-central-1.xata.sh/db/oly-001",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
