// Auto-generated — do not edit
export const variables = {
  whiteOne: "#",
  whiteTwo: "#",
  whiteThree: "#",
  whiteFour: "#",
  whiteFive: "#",
  blackOne: "#",
  blackTwo: "#",
  blackThree: "#",
  blackFour: "#",
  blackFive: "#",
  blueOne: "#",
  blueOneComplimentary: "#",
  blueOneComplimentaryTwo: "#",
  greyOne: "#",
  greyTwo: "#",
  greyThree: "#",
  greyFour: "#",
  primary: "#",
  primaryHover: "#",
  primaryHoverTwo: "#",
  primaryDisabled: "#",
  normal: "#",
  normalHover: "#",
  normalDisabled: "#",
  success: "#",
  successHover: "#",
  successDisabled: "#",
  warning: "#",
  warningHover: "#",
  warningDisabled: "#",
  danger: "#",
  dangerHover: "#",
  dangerDisabled: "#",
  info: "#",
  infoHover: "#",
  infoDisabled: "#",
  link: "#",
  body: 16,
  h0: 72,
  h1: 48,
  h2: 32,
  h3: 24,
  h4: 18,
  small: "rem(14)",
  tiny: "rem(12)",
  minMobile: 320,
  maxMobile: 767,
  minTablet: 768,
  maxTablet: 1199,
  minSmallDesktop: 1200,
  maxSmallDesktop: 1439,
  minLargeDesktop: 1440,
  maxLargeDesktop: 1951,
  minExtraLargeDesktop: 1952,
  maxExtraLargeDesktop: "null; // No max for extra-large-",
  shadowGradient: "linear-gradient(145deg, #f0f0f0, #cacaca)",
  shadowOne: "",
  shadowTwo: "",
  shadowThree: "",
  shadowFour: "",
  shadowFive: "",
  shadowSix: "",
  shadowSeven: "",
  shadowEight: "",
  transitionOne: "all 0.2s",
  transitionTwo: "all 0.3s",
  transitionThree: "all 0.5s"
} as const;

export type Variables = typeof variables;
