import { Category } from "@/sanityTemp/Types/Category"; // Importing Category type from the specified path
interface CategoryObject {
    [key: string]: any;
}

function processCategories(categories: string[]) {
    const categoryObject: CategoryObject = {};

    const formatString = (str: string) => str.replace(/[,&]/g, '').replace(/\s+/g, '');
    const toCamelCase = (str: string) => str.charAt(0).toLowerCase() + str.slice(1);
    const capitalizeFirstLetter = (str: string) => str.charAt(0).toUpperCase() + str.slice(1);

    categories.forEach(categoryStr => {
        const parts = categoryStr.split("/");
        let currentPath = "";
        const parents: string[] = []; // To store the parents of the current category

        for (let i = 0; i < parts.length; i++) {
            const category = parts[i];
            currentPath += (i === 0 ? "" : "-") + category; // Change separator to hyphen
            parents.push(category); // Add category as a parent

            if (!categoryObject[currentPath]) {
                let nickNameParts = parts.slice(0, i + 1).map((p, index) => {
                    const formattedPart = formatString(p);
                    return index === 0 ? formattedPart.toLowerCase() : toCamelCase(formattedPart);
                });
                nickNameParts[nickNameParts.length - 1] = capitalizeFirstLetter(nickNameParts[nickNameParts.length - 1]);
                const nickName = nickNameParts.join('_');

                let breadCrumbs = parts.slice(0, i).map(p => p.replace(/&/g, 'and'));

                categoryObject[currentPath] = {
                    category: category,
                    parentCategory: i > 0 ? parts[i - 1] : undefined,
                    childrenCategories: [],
                    relatedCategories: [],
                    order: i + 1,
                    nickName: nickName,
                    mainCategory: parts[0],
                    breadCrumbs: breadCrumbs,
                    seoTitle: [{
                        _type: 'block',
                        _key: 'seoTitle1',
                        children: [
                            {
                                _type: 'span',
                                _key: 'seoTitleSpan1',
                                text: category === 'For Sale' ? `Find what you're looking for on Oly: Your Trusted Classifieds Hub` : `Explore ${category} Listings on Oly — Your Trusted Classifieds Hub.`,
                            }
                        ],
                        markDefs: []
                    }],
                    seoDescription: [{
                        _type: 'block',
                        _key: 'seoDescription1',
                        children: [
                            {
                                _type: 'span',
                                _key: 'seoDescriptionSpan1',
                                text: category === 'For Sale' ? `Experience convenience and discover a wide range listings on Oly. Oly provides a user-friendly platform to explore a wide range of listings. Find exactly what you need and make your next purchase or sale hassle-free.` : `Experience convenience and variety with Oly's ${category} listings. Oly provides a user-friendly platform to explore a wide range of categories. Find exactly what you need in the ${category} category and make your next purchase or sale hassle-free.`,
                            }
                        ],
                        markDefs: []
                    }],
                    altCategoryName: currentPath, // Use currentPath directly
                    parents: [...parents], // Add parents array
                };
            }

            if (i < parts.length - 1) {
                const childCategory = parts[i + 1];
                if (!categoryObject[currentPath]?.childrenCategories.includes(childCategory)) {
                    categoryObject[currentPath]?.childrenCategories.push(childCategory);
                }
            }

            if (categoryObject[currentPath].parentCategory) {
                categoryObject[currentPath].relatedCategories.push(categoryObject[currentPath].parentCategory);
            }

            categoryObject[currentPath].relatedCategories.push(...categoryObject[currentPath].childrenCategories);
        }
    });

    return Object.values(categoryObject);
}

const categories =  [
    "For Sale/Appliances/Domestic Appliances/Irons & Ironing Boards",
    "For Sale/Apliances/Domestic Appliances/Air Purifiers & Dehumidifiers",
    "For Sale/Appliances/Small Appliances/Coffee Machines",
    "For Sale/Appliances/Small Appliances/Blenders, Processors & Mixers",
    "For Sale/Appliances/Small Appliances/Kettles & Toasters",
    "For Sale/Appliances/Small Appliances/Food & Drink Makers",
    "For Sale/Appliances/Ovens, Hobs & Cookers/Miscellaneous Ovens, Hobs & Cookers",
    "For Sale/Appliances/Ovens, Hobs & Cookers/Cookers",
    "For Sale/Appliances/Ovens, Hobs & Cookers/Hobs",
    "Services/Appliances/Ovens, Hobs & Cookers/Hobs",
];

const processedCategories = processCategories(categories);
console.log(processedCategories);







  
// const categories = [
//     "For Sale/Appliances/Domestic Appliances",
//     "For Sale/Appliances/Domestic Appliances/Heating Systems & Fireplaces",
//     "For Sale/Appliances/Domestic Appliances/Vacuum Cleaners",
//     "For Sale/Appliances/Domestic Appliances/Miscellaneous Home Appliances",
//     "For Sale/Appliances/Domestic Appliances/Air Conditioners & Fans",
//     "For Sale/Appliances/Domestic Appliances/Irons & Ironing Boards",
//     "For Sale/Appliances/Domestic Appliances/Air Purifiers & Dehumidifiers",
//     "For Sale/Appliances/Small Appliances",
//     "For Sale/Appliances/Small Appliances/Coffee Machines",
//     "For Sale/Appliances/Small Appliances/Blenders, Processors & Mixers",
//     "For Sale/Appliances/Small Appliances/Kettles & Toasters",
//     "For Sale/Appliances/Small Appliances/Food & Drink Makers",
//     "For Sale/Appliances/Small Appliances/Fryers",
//     "For Sale/Appliances/Small Appliances/Microwave Ovens",
//     "For Sale/Appliances/Small Appliances/Miscellaneous Small Appliances",
//     "For Sale/Appliances/Small Appliances/Cold Drink Preparation",
//     "For Sale/Appliances/Small Appliances/Slow Cookers",
//     "For Sale/Appliances/Small Appliances/Health Grills",
//     "For Sale/Appliances/Small Appliances/Breadmakers",
//     "For Sale/Appliances/Small Appliances/Rice Cookers",
//     "For Sale/Appliances/Ovens, Hobs & Cookers",
//     "For Sale/Appliances/Ovens, Hobs & Cookers/Miscellaneous Ovens, Hobs & Cookers",
//     "For Sale/Appliances/Ovens, Hobs & Cookers/Cookers",
//     "For Sale/Appliances/Ovens, Hobs & Cookers/Hobs",
//     "For Sale/Appliances/Ovens, Hobs & Cookers/Cooker Hoods & Splashbacks",
//     "For Sale/Appliances/Fridge Freezers",
//     "For Sale/Appliances/Washing Machines",
//     "For Sale/Appliances/Miscellaneous Appliances",
//     "For Sale/Appliances/Miscellaneous Appliances/Hair Care & Styling Appliances",
//     "For Sale/Appliances/Miscellaneous Appliances/Massage & Relaxation Appliances",
//     "For Sale/Appliances/Miscellaneous Appliances/Dental Care Appliances",
//     "For Sale/Appliances/Miscellaneous Appliances/Hair Removal & Waxing Appliances",
//     "For Sale/Appliances/Health & Beauty Appliances",
//     "For Sale/Appliances/Refrigerators",
//     "For Sale/Appliances/Tumble Dryers",
//     "For Sale/Appliances/Dishwashers",
//     "For Sale/Appliances/Freezers",
//     "For Sale/Appliances/Washer Dryers",
//     "For Sale/Appliances/Integrated Appliances",
//     "For Sale/Audio & Stereo",
//     "For Sale/Audio & Stereo/Speakers",
//     "For Sale/Audio & Stereo/Stereo Systems (whole)",
//     "For Sale/Audio & Stereo/Amps",
//     "For Sale/Audio & Stereo/Radios",
//     "For Sale/Audio & Stereo/CD, Tape & Radio (Separates)",
//     "For Sale/Audio & Stereo/Record Players/Turntables",
//     "For Sale/Audio & Stereo/Miscellaneous",
//     "For Sale/Audio & Stereo/Compact Stereos",
//     "For Sale/Baby & Kids",
//     "For Sale/Baby & Kids/Toys",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Shoes & Boots",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Miscellaneous Kids' Clothes",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Kids Coats & Jackets",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Bundle of Clothes",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Tops & Shirts",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Dresses",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Jeans & Trousers",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Kids Accessories",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Nightwear & Pyjamas",
//     "For Sale/Baby & Kids/Kids Clothes, Shoes & Accessories/Swimwear & Bathing Suits",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Lamps, Lights & Shades",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Cots & Beds",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Cribs & Bassinets",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Nursery Furniture",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Miscellaneous",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/High Chairs",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Bathtubs",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Storage",
//     "For Sale/Baby & Kids/Nursery & Children's Furniture/Changing Tables",
//     "For Sale/Baby & Kids/Baby Clothes",
//     "For Sale/Baby & Kids/Prams & Strollers",
//     "For Sale/Baby & Kids/Miscellaneous",
//     "For Sale/Baby & Kids/Car Seats & Baby Carriers",
//     "For Sale/Baby & Kids/Outdoor Toys",
//     "For Sale/Baby & Kids/Outdoor Toys/Scooters",
//     "For Sale/Baby & Kids/Outdoor Toys/Miscellaneous Outdoor Toys",
//     "For Sale/Baby & Kids/Outdoor Toys/Trampolines",
//     "For Sale/Baby & Kids/Outdoor Toys/Skateboards",
//     "For Sale/Baby & Kids/Outdoor Toys/Swings",
//     "For Sale/Baby & Kids/Outdoor Toys/Playhouses & Play Tents",
//     "For Sale/Baby & Kids/Outdoor Toys/Slides",
//     "For Sale/Baby & Kids/Outdoor Toys/Sandpits & Water Toys",
//     "For Sale/Baby & Kids/Baby Bouncers, Rockers & Swings",
//     "For Sale/Baby & Kids/Baby Bouncers, Rockers & Swings/Baby Bouncers",
//     "For Sale/Baby & Kids/Baby Bouncers, Rockers & Swings/Baby Swings",
//     "For Sale/Baby & Kids/Baby Bouncers, Rockers & Swings/Baby Rockers",
//     "For Sale/Baby & Kids/Baby Bouncers, Rockers & Swings/Baby Walkers",
//     "For Sale/Baby & Kids/Feeding",
//     "For Sale/Baby & Kids/Feeding/Miscellaneous Feeding",
//     "For Sale/Baby & Kids/Feeding/Breast Pumps",
//     "For Sale/Baby & Kids/Feeding/Sterilisers",
//     "For Sale/Baby & Kids/Feeding/Bottles",
//     "For Sale/Baby & Kids/Feeding/Bottle Warmers",
//     "For Sale/Baby & Kids/Baby & Child Safety",
//     "For Sale/Baby & Kids/Baby & Child Safety/Baby Bouncers",
//     "For Sale/Baby & Kids/Baby & Child Safety/Baby Swings",
//     "For Sale/Baby & Kids/Baby & Child Safety/Baby Rockers",
//     "For Sale/Baby & Kids/Baby & Child Safety/Baby Walkers",
//     "For Sale/Baby & Kids/Changing",
//     "For Sale/Baby & Kids/Changing/Miscellaneous Changing",
//     "For Sale/Baby & Kids/Changing/Changing Bags",
//     "For Sale/Baby & Kids/Changing/Potties",
//     "For Sale/Baby & Kids/Changing/Changing Mats",
//     "For Sale/Cameras, Camcorders & Studio Equipment",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Digital Cameras",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Miscellaneous Cameras & Accessories",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Surveillance Cameras",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Lenses",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Miscellaneous Camera Accessories",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Cases, Bags & Covers",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Memory Cards & Readers",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Batteries",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Accessory Bundles",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Cables & Adapters",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camera Accessories/Chargers & Docks",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Tripods & Supports",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Film & Disposable Cameras",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Camcorders & Video Cameras",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Lighting & Studio",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Telescopes",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Binoculars & Scopes",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Flashguns & Accessories",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Digital Photo Frames",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Filters",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Grips",
//     "For Sale/Cameras, Camcorders & Studio Equipment/Replacement Parts & Tools",
//     "For Sale/Christmas Decorations",
//     "For Sale/Clothes, Footwear & Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Dresses",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Coats & Jackets",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Tops & Shirts",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Miscellaneous Women's Clothing",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Jumpers & Cardigans",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Trousers",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Jeans",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Skirts",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Activewear",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Hoodies & Sweats",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Bundles",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Jumpsuits & Playsuits",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/T-Shirts",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Swimwear",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Shorts",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Maternity",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Leggings",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Suits & Tailoring",
//     "For Sale/Clothes, Footwear & Accessories/Women's Clothing/Waistcoats",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Coats & Jackets",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/T-Shirts",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Casual Shirts & Tops",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Hoodies & Sweats",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Suits & Tailoring",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Activewear",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Jeans",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Trousers",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Miscellaneous Men's Clothing",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Fancy Dress & Period Costume",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Shorts",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Jumpers & Cardigans",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Formal Shirts",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Clothes Bundles",
//     "For Sale/Clothes, Footwear & Accessories/Men's Clothing/Waistcoats",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Trainers",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Boots",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Heels",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Sandals & Beach",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Flats",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Miscellaneous Women's",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Slippers",
//     "For Sale/Clothes, Footwear & Accessories/Women's Shoes/Shoe Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Jewellery",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Women's Bags & Handbags",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Purses & Wallets",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Scarves & Shawls",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Hats",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Miscellaneous Women's Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Belts",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Wigs, Extensions & Supplies",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Gloves",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Hair Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Women's Accessories/Fascinators & Headpieces",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Trainers",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Boots",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Casual Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Formal Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Miscellaneous Men's Shoes & Boots",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Slippers",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Sandals & Beach Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Men's Shoes & Boots/Men's Shoe Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Watches",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Bags, Rucksacks & Satchels",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Hats & Caps",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Miscellaneous Men's Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Wallets",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Ties & Cravats",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Belts",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Sunglasses",
//     "For Sale/Clothes, Footwear & Accessories/Men's Accessories/Men's Gloves",
//     "For Sale/Clothes, Footwear & Accessories/Men's Watches",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Wedding Dresses",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Bridesmaid Dresses",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Bridal Accessories",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Mother of the Bride",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Formal Hats & Fascinators",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Grooms Outfits & Suits",
//     "For Sale/Clothes, Footwear & Accessories/Wedding Clothes & Accessories/Bridal Shoes",
//     "For Sale/Clothes, Footwear & Accessories/Miscellaneous",
//     "For Sale/Clothes, Footwear & Accessories/Sunglasses",
//     "For Sale/Computers & Software",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/PC Laptops & Netbooks",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Desktop & Workstation PCs",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Monitors & Projectors",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Tablets, eBooks & eReaders",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Keyboards, Mice & Input Devices",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Printers & Scanners",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Laptop Accessories",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Modems, Broadband & Networking",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Apple Laptops",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Memory, Motherboards & Processors",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Hard Drives",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Video Cards & Sound Cards",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Tablet, eBook & eReader Accessories",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/Servers",
//     "For Sale/Computers & Software/Computers, Laptops & Netbooks/PDAs, Handhelds & Accessories",
//     "For Sale/Computers & Software/Software",
//     "For Sale/Computers & Software/Software/Miscellaneous Software",
//     "For Sale/Computers & Software/Software/Image, Video & Audio Editing",
//     "For Sale/Computers & Software/Software/Operating Systems",
//     "For Sale/Computers & Software/Software/Office & Business",
//     "For Sale/Computers & Software/Software/Antivirus Software",
//     "For Sale/DIY Tools & Materials",
//     "For Sale/DIY Tools & Materials/Power Tools",
//     "For Sale/DIY Tools & Materials/Power Tools/Miscellaneous Power Tools",
//     "For Sale/DIY Tools & Materials/Power Tools/Drills",
//     "For Sale/DIY Tools & Materials/Power Tools/Saws",
//     "For Sale/DIY Tools & Materials/Power Tools/Grinders",
//     "For Sale/DIY Tools & Materials/Power Tools/Generators",
//     "For Sale/DIY Tools & Materials/Power Tools/Welding Equipment",
//     "For Sale/DIY Tools & Materials/Power Tools/Sanders",
//     "For Sale/DIY Tools & Materials/Power Tools/Routers",
//     "For Sale/DIY Tools & Materials/Power Tools/Air Compressors",
//     "For Sale/DIY Tools & Materials/Power Tools/Nailers & Staplers",
//     "For Sale/DIY Tools & Materials/Power Tools/Lathes",
//     "For Sale/DIY Tools & Materials/Power Tools/Planers",
//     "For Sale/DIY Tools & Materials/Power Tools/Concrete Mixers",
//     "For Sale/DIY Tools & Materials/Power Tools/Power Tool Sets",
//     "For Sale/DIY Tools & Materials/Power Tools/Tile Cutters",
//     "For Sale/DIY Tools & Materials/Power Tools/Wet Dry Vacuums",
//     "For Sale/DIY Tools & Materials/Power Tools/Power Screwdrivers",
//     "For Sale/DIY Tools & Materials/Power Tools/Rotary Hammers",
//     "For Sale/DIY Tools & Materials/Power Tools/Polishers",
//     "For Sale/DIY Tools & Materials/Power Tools/Hot Air Guns",
//     "For Sale/DIY Tools & Materials/Power Tools/Combo Kits",
//     "For Sale/DIY Tools & Materials/Power Tools/Water Pumps",
//     "For Sale/DIY Tools & Materials/Power Tools/Soldering Equipment",
//     "For Sale/DIY Tools & Materials/Power Tools/Jointers",
//     "For Sale/DIY Tools & Materials/Building Materials",
//     "For Sale/DIY Tools & Materials/Building Materials/Miscellaneous Building Materials",
//     "For Sale/DIY Tools & Materials/Building Materials/Roofing & Ventilation",
//     "For Sale/DIY Tools & Materials/Building Materials/Tiles",
//     "For Sale/DIY Tools & Materials/Building Materials/Bricks, Blocks & Lintels",
//     "For Sale/DIY Tools & Materials/Building Materials/Insulation",
//     "For Sale/DIY Tools & Materials/Building Materials/Guttering & Drainage",
//     "For Sale/DIY Tools & Materials/Building Materials/Cement, Mortar & Aggregates",
//     "For Sale/DIY Tools & Materials/Building Materials/Sheet Materials",
//     "For Sale/DIY Tools & Materials/Building Materials/Plaster & Plasterboard",
//     "For Sale/DIY Tools & Materials/Building Materials/Building Chemicals",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Sinks & Basins",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Shower Fixtures",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Bathroom Taps & Mixers",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Tiles",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Toilets, Toilet Seats & Bidets",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Miscellaneous Bathroom Fixtures",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Towel Radiators",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Bathroom Suites",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Bath Shower Screens",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Cabinets & Storage",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Bath Panels",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Shelves",
//     "For Sale/DIY Tools & Materials/Bathroom Fixtures/Units",
//     "For Sale/DIY Tools & Materials/Wood & Timber",
//     "For Sale/DIY Tools & Materials/Hand Tools",
//     "For Sale/DIY Tools & Materials/Hand Tools/Miscellaneous Hand Tools",
//     "For Sale/DIY Tools & Materials/Hand Tools/Hand Tool Sets & Kits",
//     "For Sale/DIY Tools & Materials/Hand Tools/Spanners & Wrenches",
//     "For Sale/DIY Tools & Materials/Hand Tools/Clamps & Vices",
//     "For Sale/DIY Tools & Materials/Hand Tools/Saws",
//     "For Sale/DIY Tools & Materials/Hand Tools/Chisels, Planes & Surform",
//     "For Sale/DIY Tools & Materials/Hand Tools/Screwdrivers & Nut Drivers",
//     "For Sale/DIY Tools & Materials/Hand Tools/Hammers & Mallets",
//     "For Sale/DIY Tools & Materials/Hand Tools/Masonry & Tiling Tools",
//     "For Sale/DIY Tools & Materials/Hand Tools/Sanding, Scrubs & Brushes",
//     "For Sale/DIY Tools & Materials/Doors & Windows",
//     "For Sale/DIY Tools & Materials/Plumbing & Central Heating",
//     "For Sale/DIY Tools & Materials/Garden Power Tools",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Lawn Mowers",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Hedge Trimmers",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Pressure Washers",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Chainsaws",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Grass Trimmers",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Leaf Blowers & Vacuums",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Miscellaneous Garden Power Tools",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Garden Shredders",
//     "For Sale/DIY Tools & Materials/Garden Power Tools/Pond Pumps & Accessories",
//     "For Sale/DIY Tools & Materials/Tool Storage & Workbenches",
//     "For Sale/DIY Tools & Materials/Screws & Fixings",
//     "For Sale/DIY Tools & Materials/Ladders & Handtrucks",
//     "For Sale/DIY Tools & Materials/Protective Clothing & Workwear",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Miscellaneous Garden Hand Tools",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Shovel & Spades",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Shears & Loppers",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Wheelbarrows & Trolleys",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Rakes & Hoes",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Hoses & Hose Reels",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Forks",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Tool Sets",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Secateurs & Pruners",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Planters",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Weeding Tools",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Gloves, Trugs & Accessories",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Trowels, Floats & Hawks",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Composters & Bins",
//     "For Sale/DIY Tools & Materials/Garden Hand Tools/Watering Cans",
//     "For Sale/DIY Tools & Materials/Railway Sleepers",
//     "For Sale/Health & Beauty",
//     "For Sale/Health & Beauty/Mobility, Disability & Medical",
//     "For Sale/Health & Beauty/Fragrances",
//     "For Sale/Health & Beauty/Hair Care & Styling",
//     "For Sale/Health & Beauty/Make Up & Cosmetics",
//     "For Sale/Health & Beauty/Health Care",
//     "For Sale/Health & Beauty/Bath & Body",
//     "For Sale/Health & Beauty/Massage Products",
//     "For Sale/Health & Beauty/Facial Skin Care",
//     "For Sale/Health & Beauty/Manicure & Pedicure",
//     "For Sale/Health & Beauty/Shaving & Hair Removal",
//     "For Sale/Health & Beauty/Diet & Weight Loss",
//     "For Sale/Health & Beauty/Vitamins & Supplements",
//     "For Sale/Health & Beauty/Sun Care & Tanning",
//     "For Sale/Health & Beauty/Dental Care",
//     "For Sale/Health & Beauty/Tattoo & Body Art",
//     "For Sale/Health & Beauty/Vision & Eye Care",
//     "For Sale/Home & Garden",
//     "For Sale/Home & Garden/Dining, Living Room Furniture",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Sofas, Armchairs & Suites",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Mirrors, Clocks & Ornaments",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Paintings & Pictures",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Dining Tables & Chairs",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Miscellaneous",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Chairs, Stools & Miscellaneous Seating",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Lighting & Fittings",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Coffee table",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Curtains, Blinds & Windows",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Carpets & Flooring",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Sofa Beds & Futons",
//     "For Sale/Home & Garden/Dining, Living Room Furniture/Tableware",
//     "For Sale/Home & Garden/Miscellaneous Household Goods",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Wardrobes, Shelving & Storage",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Double Beds",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Dressers & Chests",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Single Beds",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Linen & Bedding",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Miscellaneous Bedroom Furniture & Accs",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Bedside Tables",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Mattresses",
//     "For Sale/Home & Garden/Beds & Bedroom Furniture/Chests & Trunks",
//     "For Sale/Home & Garden/Kitchenware & Accessories",
//     "For Sale/Home & Garden/Kitchenware & Accessories/Tableware",
//     "For Sale/Home & Garden/Kitchenware & Accessories/Kitchen Storage",
//     "For Sale/Home & Garden/Kitchenware & Accessories/Cookware",
//     "For Sale/Home & Garden/Kitchenware & Accessories/Kitchen Accessories",
//     "For Sale/Home & Garden/Kitchenware & Accessories/Laundry Accessories",
//     "For Sale/Home & Garden/Garden & Patio",
//     "For Sale/Home & Garden/Garden & Patio/Garden Building & Decoration",
//     "For Sale/Home & Garden/Garden & Patio/Outdoor Settings & Furniture",
//     "For Sale/Home & Garden/Garden & Patio/Garden & Patio Furniture",
//     "For Sale/Home & Garden/Garden & Patio/Lawnmowers & Trimmers",
//     "For Sale/Home & Garden/Garden & Patio/Barbeques & Outdoor Heaters",
//     "For Sale/Home & Garden/Garden & Patio/Hoses",
//     "For Sale/House Clearance",
//     "For Sale/Music, Films, Books & Games",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines/Books",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines/Comics",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines/Magazines",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines/Miscellaneous Books, Comics & Magazines",
//     "For Sale/Music, Films, Books & Games/Books, Comics & Magazines/Audio Books",
//     "For Sale/Music, Films, Books & Games/Music",
//     "For Sale/Music, Films, Books & Games/Music/Vinyl",
//     "For Sale/Music, Films, Books & Games/Music/CDs",
//     "For Sale/Music, Films, Books & Games/Music/Miscellaneous Music",
//     "For Sale/Music, Films, Books & Games/Music/Cassettes",
//     "For Sale/Music, Films, Books & Games/Films & TV",
//     "For Sale/Music, Films, Books & Games/Films & TV/DVDs",
//     "For Sale/Music, Films, Books & Games/Films & TV/VHS Tapes",
//     "For Sale/Music, Films, Books & Games/Films & TV/Blu-rays",
//     "For Sale/Music, Films, Books & Games/Games & Board Games",
//     "For Sale/Music, Films, Books & Games/Miscellaneous Music, Films, Books & Games",
//     "For Sale/Musical Instruments & DJ Equipment",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Guitars",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Miscellaneous Guitars & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Bass Amplifiers",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Cases",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Parts",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Bass Effects",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Pickups",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Plectrums/Picks",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Strings",
//     "For Sale/Musical Instruments & DJ Equipment/Guitars & Accessories/Straps",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Electric Keyboards",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Pianos",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Accordians",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Miscellaneous Keyboards, Pianos, Organs & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Organs",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Keyboard Stands",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Covers & Cases",
//     "For Sale/Musical Instruments & DJ Equipment/Keyboards & Pianos/Piano Stools",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Speakers & Monitors",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Synthesizers",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Miscellaneous Studio Equipment",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Effects",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Audio/MIDI Interfaces",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Audio/MIDI Controllers",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Recorders",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Samplers & Sequencers",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Drum Machines",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Stands & Supports",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Preamps",
//     "For Sale/Musical Instruments & DJ Equipment/Studio & Live Music Equipment/Parts & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drums",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Cymbals",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Miscellaneous Percussion & Drums",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drum Mounts & Hardware",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drum Pedals",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drum Heads & Skins",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Bags & Cases",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drum Stands",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Drum Sticks",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Tambourines",
//     "For Sale/Musical Instruments & DJ Equipment/Percussion & Drums/Xylophones & Glockenspiels",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Decks & Turntables",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Miscellaneous DJ Equipment & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Mixers",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Stage Lightings & Effects",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Karaoke Equipment",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Stands & Supports",
//     "For Sale/Musical Instruments & DJ Equipment/Performance & DJ Equipment/Parts & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Violins",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Ukulele",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Banjos",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Miscellaneous String Musical Instruments",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Cellos",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Mandolins",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/String Instrument Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/String Musical Instruments/Double Bass",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Saxophone",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Flute",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Clarinet",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Miscellaneous Woodwind Instruments & Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Bagpipes",
//     "For Sale/Musical Instruments & DJ Equipment/Woodwind Musical Instruments/Oboe",
//     "For Sale/Musical Instruments & DJ Equipment/Miscellaneous",
//     "For Sale/Musical Instruments & DJ Equipment/Sheet Music & Song Books",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments/Trumpet",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments/Miscellaneous Brass Instruments",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments/Brass Instrument Accessories",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments/Trombone",
//     "For Sale/Musical Instruments & DJ Equipment/Brass Musical Instruments/Cornet",
//     "For Sale/Office Furniture & Equipment",
//     "For Sale/Office Furniture & Equipment/Office Furniture",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Desks & Tables",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Chairs",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Storage & Filing Cabinets",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Bookshelves",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Miscellaneous Furniture",
//     "For Sale/Office Furniture & Equipment/Office Furniture/Cubicles & Partitions",
//     "For Sale/Office Furniture & Equipment/Restaurant & Catering Equipment",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Printers",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Miscellaneous Office Equipment",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Ink Cartridges & Toners",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Desk Supplies & Equipment",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Shredders",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Calculators",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Flipcharts & Whiteboards",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Faxes Machines",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Scanners & Copiers",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Staplers",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Label Markers",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Projectors",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Scanners",
//     "For Sale/Office Furniture & Equipment/Supplies, Equipment & Stationery/Mouse Mats & Wrist Rests",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Cash Registers & Supplies",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Shelving & Racking",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Retail Display",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Mannequins",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Miscellaneous Retail & Shop Fittings",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Advertising & Shop Signs",
//     "For Sale/Office Furniture & Equipment/Retail & Shop Fittings/Signs",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Boxes",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Envelopes",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Miscellaneous Packing & Mailing Supplies",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Mailing Bags, Pouches & Sacks",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Bubble & Foam Wrap",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Packing Tape",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Address Labels",
//     "For Sale/Office Furniture & Equipment/Packaging & Mailing Supplies/Paper Bags & Gift Bags",
//     "For Sale/Office Furniture & Equipment/Business For Sale",
//     "For Sale/Office Furniture & Equipment/Medical & Laboratory Equipment",
//     "For Sale/Office Furniture & Equipment/Catering trailer",
//     "For Sale/Phones, Mobile Phones & Telecoms",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Apple iPhone",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Samsung",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Miscellaneous",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Nokia",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Motorola",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Sony Ericsson",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/HTC",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Blackberry",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/LG",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Vodafone",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Siemens",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/Orange",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phones/O2, XDA",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Cases & Covers",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Chargers & Docks",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Headsets",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Cables & Adapters",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Miscellaneous Accessories",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Screen Protectors",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Holders & Mounts",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Batteries",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Memory Cards",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Accessory Bundles",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Audio Docks & Speakers",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Styluses",
//     "For Sale/Phones, Mobile Phones & Telecoms/Mobile Phone Accessories/Car Speakerphones",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines/Miscellaneous Phones & Accessories",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines/Answering Machines",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines/Cables & Adapters",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines/Phone Sockets",
//     "For Sale/Phones, Mobile Phones & Telecoms/Home Phones & Answering Machines/Batteries",
//     "For Sale/Phones, Mobile Phones & Telecoms/Smart Watch",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/Walkie Talkies",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/Ham/Amateur Radios",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/CB Radios",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/Miscellaneous Radio Equipment",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/Antennas",
//     "For Sale/Phones, Mobile Phones & Telecoms/Radio Communication Equipment/Parts & Accessories",
//     "For Sale/Phones, Mobile Phones & Telecoms/SIM Cards",
//     "For Sale/Sports, Recreation & Travel",
//     "For Sale/Sports, Recreation & Travel/Bicycles",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Fitness Equipment",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Weights",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Machines",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Yoga & Pilates",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Multi-Gyms",
//     "For Sale/Sports, Recreation & Travel/Fitness & Gym Equipment/Miscellaneous Fitness & Gym Equipment",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Clubs",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Balls",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Miscellaneous Golf Equipment",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Bags",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Carts & Trolleys",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Sets",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Shoes",
//     "For Sale/Sports, Recreation & Travel/Golf Equipment/Club Components",
//     "For Sale/Sports, Recreation & Travel/Bicycle Accessories",
//     "For Sale/Sports, Recreation & Travel/Water Sports",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Boats, Kayaks & Jet Skis",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Wetsuits & Accessories",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Sailing Equipment",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Surfboards & Windsurfs",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Diving Equipment",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Paddle board",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Waterskiing & Wakeboarding",
//     "For Sale/Sports, Recreation & Travel/Water Sports/Rowing Equipment",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Miscellaneous Fishing Equipment",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Rods",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Reels",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Tackle",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Rod & Reel Combos",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Lures & Flies",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Fishing Chairs",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Combo & Sets",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Nets",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Waders & Boots",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Line",
//     "For Sale/Sports, Recreation & Travel/Fishing Equipment/Pods",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Football",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Cricket",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Tennis, Squash & Badminton",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Pool & Snooker",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Hockey",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Basketball",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Rugby",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Badminton",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Bowls",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Table Tennis",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Squash",
//     "For Sale/Sports, Recreation & Travel/Ball & Racquet Sport Equipment/Volleyball",
//     "For Sale/Sports, Recreation & Travel/Miscellaneous Sports & Leisure",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Camping Gear",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Tents",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Camping Beds & Mats",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Sleeping Bags & Equipment",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Binoculars",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Kitchen",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Clothing & Boots",
//     "For Sale/Sports, Recreation & Travel/Camping & Hiking/Toilets",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment/Suitcases",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment/Backpacks",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment/Sports Bags",
//     "For Sale/Sports, Recreation & Travel/Luggage & Travel Equipment/Business Cases",
//     "For Sale/Sports, Recreation & Travel/Winter Sports",
//     "For Sale/Sports, Recreation & Travel/Winter Sports/Skis, Boots, Bindings & Poles",
//     "For Sale/Sports, Recreation & Travel/Winter Sports/Clothing & Accessories",
//     "For Sale/Sports, Recreation & Travel/Winter Sports/Snowboards, Boots & Bindings",
//     "For Sale/Sports, Recreation & Travel/Winter Sports/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Inline Skates & Skateboards",
//     "For Sale/Sports, Recreation & Travel/Electric bikes",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Gloves",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Punch Bags",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Protective Gear",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Miscellaneous",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Punch & Kick Pads",
//     "For Sale/Sports, Recreation & Travel/Boxing & Martial Arts Equipment/Sets",
//     "For Sale/Sports, Recreation & Travel/Electric scooters",
//     "For Sale/Sports, Recreation & Travel/Scooters",
//     "For Sale/Sports, Recreation & Travel/Gym Memberships",
//     "For Sale/Tickets",
//     "For Sale/Tickets/Concerts",
//     "For Sale/Tickets/Concerts/Miscellaneous Concert Tickets",
//     "For Sale/Tickets/Concerts/Pop",
//     "For Sale/Tickets/Concerts/Music Festivals",
//     "For Sale/Tickets/Concerts/Rock & Metal",
//     "For Sale/Tickets/Concerts/Dance",
//     "For Sale/Tickets/Concerts/Hip-Hop & R&B",
//     "For Sale/Tickets/Concerts/Classical",
//     "For Sale/Tickets/Concerts/Jazz & Blues",
//     "For Sale/Tickets/Comedy & Theatre",
//     "For Sale/Tickets/Days Out",
//     "For Sale/Tickets/Sports",
//     "For Sale/Tickets/Sports/Horse Racing",
//     "For Sale/Tickets/Sports/Fight & Wrestling",
//     "For Sale/Tickets/Sports/Miscellaneous Sports Tickets",
//     "For Sale/Tickets/Sports/Cricket",
//     "For Sale/Tickets/Sports/Motorsports",
//     "For Sale/Tickets/Sports/Rugby",
//     "For Sale/Tickets/Sports/Athletics",
//     "For Sale/Tickets/Sports/Tennis",
//     "For Sale/Tickets/Travel",
//     "For Sale/Tickets/Travel/Holidays & Hotels",
//     "For Sale/Tickets/Travel/Flight Tickets",
//     "For Sale/TV, DVD, Blu-Ray",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories/TV Mounts & Stands",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories/Cables & Connectors",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories/Remote Controls",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories/Miscellaneous TV & DVD Accessories",
//     "For Sale/TV, DVD, Blu-Ray/TV, DVD & VCR Accessories/3D TV Glasses & Accessories",
//     "For Sale/TV, DVD, Blu-Ray/Televisions, Plasma & LCD TVs",
//     "For Sale/TV, DVD, Blu-Ray/Smart TV",
//     "For Sale/TV, DVD, Blu-Ray/Miscellaneous TV, DVD & Video",
//     "For Sale/TV, DVD, Blu-Ray/DVD Players & Recorders",
//     "For Sale/TV, DVD, Blu-Ray/TV Reception & Set-Top Boxes",
//     "For Sale/TV, DVD, Blu-Ray/Satellite & Cable Equipment",
//     "For Sale/TV, DVD, Blu-Ray/Security & Surveillance Systems",
//     "For Sale/TV, DVD, Blu-Ray/Blu-ray Players & Recorders",
//     "For Sale/TV, DVD, Blu-Ray/TV Projectors",
//     "For Sale/TV, DVD, Blu-Ray/Video Players & Recorders",
//     "For Sale/TV, DVD, Blu-Ray/GPS Devices",
//     "For Sale/TV, DVD, Blu-Ray/Portable DVD & Blu-ray Players",
//     "For Sale/Video Games & Consoles",
//     "For Sale/Video Games & Consoles/Consoles",
//     "For Sale/Video Games & Consoles/Consoles/PS4 (Sony Playstation 4)",
//     "For Sale/Video Games & Consoles/Consoles/Xbox One",
//     "For Sale/Video Games & Consoles/Consoles/Miscellaneous Consoles",
//     "For Sale/Video Games & Consoles/Consoles/PS5 (Sony PlayStation 5)",
//     "For Sale/Video Games & Consoles/Consoles/Xbox 360 & Xbox",
//     "For Sale/Video Games & Consoles/Consoles/Nintendo Wii",
//     "For Sale/Video Games & Consoles/Consoles/PS3 (Sony PlayStation 3)",
//     "For Sale/Video Games & Consoles/Consoles/PS2 & PS1 (Sony PlayStation 2 & 1)",
//     "For Sale/Video Games & Consoles/Consoles/Nintendo DS & DSi",
//     "For Sale/Video Games & Consoles/Consoles/Sega",
//     "For Sale/Video Games & Consoles/Consoles/PSP (Sony PlayStation Portable)",
//     "For Sale/Video Games & Consoles/Consoles/Nintendo 3DS",
//     "For Sale/Video Games & Consoles/Consoles/Nintendo Wii U",
//     "For Sale/Video Games & Consoles/Consoles/PS Vita (Sony PlayStation Vita)",
//     "For Sale/Video Games & Consoles/Consoles/Atari",
//     "For Sale/Video Games & Consoles/Games",
//     "For Sale/Video Games & Consoles/Video Game Accessories",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Video Game Controllers",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Miscellaneous Video Game Accessories",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Video Game Accessory Bundles",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Video Games Cables & Adapters",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Video Games Motion Sensors & Cameras",
//     "For Sale/Video Games & Consoles/Video Game Accessories/Video Game Cases, Covers & Bags",
//     "For Sale/Video Games & Consoles/Miscellaneous Video Games & Consoles",
//     "For Sale/Video Games & Consoles/Gaming Merchandise",
//     "For Sale/Video Games & Consoles/Replacement Parts & Tools",
//     "For Sale/Freebies",
//     "For Sale/Miscellaneous Goods",
//     "For Sale/Miscellaneous Goods/Hobbies, Interests & Collectibles",
//     "For Sale/Miscellaneous Goods/Miscellaneous",
//     "For Sale/Miscellaneous Goods/Antiques",
//     "For Sale/Miscellaneous Goods/Scrapbooking, Sewing, Art, Craft",
//     "For Sale/Miscellaneous Goods/Aquariums",
//     "For Sale/Miscellaneous Goods/Drones",
//     "For Sale/Miscellaneous Goods/Health & Beauty",
//     "For Sale/Wanted",
//     "For Sale/Wanted/Miscellaneous",
//     "For Sale/Wanted/Computing & Phones",
//     "For Sale/Wanted/Household",
//     "For Sale/Wanted/Audio & Vision",
//     "For Sale/Wanted/Sports & Leisure",
//     "For Sale/Wanted/Transport",
//     "For Sale/Swap Shop",
//     "Property/For Sale",
//     "Property/To Rent",
//     "Property/To Share",
//     "Property/Commercial",
//     "Property/International",
//     "Property/Holiday Rentals",
//     "Property/Property Wanted",
//     "Property/Developments",
//     "Property/Parking & Garage",
//     "Job/Driving & Automotive",
//     "Job/Driving & Automotive/Sales & Aftercare",
//     "Job/Driving & Automotive/Mechanics & Technicians",
//     "Job/Driving & Automotive/Drivers & Instructors",
//     "Job/Engineering",
//     "Job/Engineering/Mechanical Engineers",
//     "Job/Engineering/Electrical Engineers",
//     "Job/Engineering/Civil Engineers",
//     "Job/Financial Services",
//     "Job/Gardening",
//     "Job/Health & Beauty",
//     "Job/Health & Beauty/Hairdressing",
//     "Job/Health & Beauty/Massage Therapists",
//     "Job/Health & Beauty/Beauty Therapists",
//     "Job/Health & Beauty/Spa",
//     "Job/Health & Beauty/Salon",
//     "Job/Healthcare & Medical",
//     "Job/Healthcare & Medical/Dentist & Dental Hygiene",
//     "Job/Healthcare & Medical/Nursing",
//     "Job/Healthcare & Medical/Hospital",
//     "Job/Healthcare & Medical/Pharmaceutical",
//     "Job/Hospitality & Catering",
//     "Job/Hospitality & Catering/Chefs",
//     "Job/Hospitality & Catering/Pubs & Bars",
//     "Job/Hospitality & Catering/Restaurant",
//     "Job/Hospitality & Catering/Hotel",
//     "Job/Hospitality & Catering/Catering",
//     "Job/Hospitality & Catering/Events",
//     "Job/Housekeeping & Cleaning",
//     "Job/Housekeeping & Cleaning/Domestic",
//     "Job/Housekeeping & Cleaning/Commercial",
//     "Job/HR",
//     "Job/Legal",
//     "Job/Leisure & Tourism",
//     "Job/Leisure & Tourism/Tourism",
//     "Job/Leisure & Tourism/Leisure",
//     "Job/Manufacturing & Industrial",
//     "Job/Manufacturing & Industrial/Assemblers",
//     "Job/Manufacturing & Industrial/Metal Workers",
//     "Job/Marketing, Advertising & PR",
//     "Job/Marketing, Advertising & PR/Marketing",
//     "Job/Marketing, Advertising & PR/Market Research & Telemarketing",
//     "Job/Marketing, Advertising & PR/Digital Marketing",
//     "Job/Marketing, Advertising & PR/PR",
//     "Job/Media, Digital & Creative",
//     "Job/Media, Digital & Creative/Media",
//     "Job/Media, Digital & Creative/Designers",
//     "Job/Media, Digital & Creative/Photographers",
//     "Job/Performing Arts",
//     "Job/Performing Arts/Modelling",
//     "Job/Performing Arts/Acting",
//     "Job/Performing Arts/Entertainment",
//     "Job/Performing Arts/Musician",
//     "Job/Purchasing & Procurement",
//     "Job/Recruitment",
//     "Job/Retail & FMCG",
//     "Job/Sales",
//     "Job/Scientific & Research",
//     "Job/Security",
//     "Job/Social & Care Work",
//     "Job/Social & Care Work/Carers",
//     "Job/Social & Care Work/Social Care",
//     "Job/Sport, Fitness & and Outdoor Activities",
//     "Job/Teaching & Education",
//     "Job/Teaching & Education/Tutor",
//     "Job/Teaching & Education/Nursery",
//     "Job/Teaching & Education/Secondary",
//     "Job/Teaching & Education/Further Education",
//     "Job/Teaching & Education/Primary",
//     "Job/Teaching & Education/Higher Education",
//     "Job/Transport, Logistics & Delivery",
//     "Job/Transport, Logistics & Delivery/Logistics",
//     "Job/Transport, Logistics & Delivery/Delivery Drivers",
//     "Job/Transport, Logistics & Delivery/Warehouse",
//     "Job/Transport, Logistics & Delivery/Machine Driving",
//     "Services/Tradesmen & Construction",
//     "Services/Tradesmen & Construction/Removal Services",
//     "Services/Tradesmen & Construction/Handymen",
//     "Services/Tradesmen & Construction/Painting & Decorating",
//     "Services/Tradesmen & Construction/Plumbing",
//     "Services/Tradesmen & Construction/Builders",
//     "Services/Tradesmen & Construction/Pest & Vermin Control",
//     "Services/Tradesmen & Construction/Electricians",
//     "Services/Tradesmen & Construction/Gardening & Landscaping",
//     "Services/Tradesmen & Construction/Plasterers",
//     "Services/Tradesmen & Construction/Carpentry & Joiners",
//     "Services/Tradesmen & Construction/Flooring",
//     "Services/Tradesmen & Construction/Locksmiths",
//     "Services/Tradesmen & Construction/Architect",
//     "Services/Tradesmen & Construction/Tilers",
//     "Services/Tradesmen & Construction/Roofing",
//     "Services/Tradesmen & Construction/Bathroom Fitters",
//     "Services/Tradesmen & Construction/Groundworkers",
//     "Services/Tradesmen & Construction/Flatpack Furniture Assemblers",
//     "Services/Tradesmen & Construction/Kitchen Fitters",
//     "Services/Tradesmen & Construction/Bricklayers",
//     "Services/Tradesmen & Construction/Tree Surgeons",
//     "Services/Tradesmen & Construction/Scaffolding",
//     "Services/Tradesmen & Construction/Airconditioning & Heating",
//     "Services/Tradesmen & Construction/Skip Hire",
//     "Services/Tradesmen & Construction/Paving & Driveway",
//     "Services/Tradesmen & Construction/Fencing Contractors",
//     "Services/Tradesmen & Construction/Windows & Doors",
//     "Services/Tradesmen & Construction/Loft Conversion Specialists",
//     "Services/Tradesmen & Construction/Surveyors",
//     "Services/Tradesmen & Construction/Stonemasons",
//     "Services/Tradesmen & Construction/Structural Engineers",
//     "Services/Tradesmen & Construction/Bedroom Fitters",
//     "Services/Tradesmen & Construction/Blacksmiths",
//     "Services/Tradesmen & Construction/Chimney Sweeps",
//     "Services/Tradesmen & Construction/Shopfitters",
//     "Services/Tradesmen & Construction/Glaziers",
//     "Services/Tradesmen & Construction/Overseas Removals",
//     "Services/Tradesmen & Construction/Architect",
//     "Services/Tradesmen & Construction/Locksmiths",
//     "Services/Tradesmen & Construction/Flooring",
//     "Services/Tradesmen & Construction/Roofing",
//     "Services/Tradesmen & Construction/Tilers",
//     "Services/Tradesmen & Construction/Groundworkers",
//     "Services/Tradesmen & Construction/Bathroom Fitters",
//     "Services/Tradesmen & Construction/Flatpack Furniture Assemblers",
//     "Services/Tradesmen & Construction/Kitchen Fitters",
//     "Services/Tradesmen & Construction/Bricklayers",
//     "Services/Tradesmen & Construction/Tree Surgeons",
//     "Services/Tradesmen & Construction/Loft Conversion Specialists",
//     "Services/Tradesmen & Construction/Fencing Contractors",
//     "Services/Tradesmen & Construction/Paving & Driveway",
//     "Services/Tradesmen & Construction/Airconditioning & Heating",
//     "Services/Tradesmen & Construction/Skip Hire",
//     "Services/Tradesmen & Construction/Scaffolding",
//     "Services/Tradesmen & Construction/Stonemasons",
//     "Services/Tradesmen & Construction/Shopfitters",
//     "Services/Tradesmen & Construction/Windows & Doors",
//     "Services/Tradesmen & Construction/Structural Engineers",
//     "Services/Tradesmen & Construction/Blacksmiths",
//     "Services/Tradesmen & Construction/Surveyors",
//     "Services/Tradesmen & Construction/Bedroom Fitters",
//     "Services/Tradesmen & Construction/Glaziers",
//     "Services/Tradesmen & Construction/Chimney Sweeps",
//     "Services/Tradesmen & Construction/Lighting Specialists",
//     "Services/Tuition & Classes",
//     "Services/Tuition & Classes/Academic",
//     "Services/Tuition & Classes/Language",
//     "Services/Tuition & Classes/Language/English",
//     "Services/Tuition & Classes/Language/Spanish",
//     "Services/Tuition & Classes/Language/French",
//     "Services/Tuition & Classes/Language/Italian",
//     "Services/Tuition & Classes/Language/Miscellaneous Language Lessons",
//     "Services/Tuition & Classes/Language/German",
//     "Services/Tuition & Classes/Language/Japanese",
//     "Services/Tuition & Classes/Language/Chinese",
//     "Services/Tuition & Classes/Language/Dutch",
//     "Services/Tuition & Classes/Language/Polish",
//     "Services/Tuition & Classes/Language/Russian",
//     "Services/Tuition & Classes/Language/IsiXhosa",
//     "Services/Tuition & Classes/Language/Afrikaans",
//     "Services/Tuition & Classes/Language/isiNdebele",
//     "Services/Tuition & Classes/Language/isiZulu",
//     "Services/Tuition & Classes/Language/Sesotho",
//     "Services/Tuition & Classes/Language/Sepedi",
//     "Services/Tuition & Classes/Language/Setswana",
//     "Services/Tuition & Classes/Language/siSwati",
//     "Services/Tuition & Classes/Language/Tshivenda",
//     "Services/Tuition & Classes/Language/Xitsonga",
//     "Services/Tuition & Classes/Language/Somali",
//     "Services/Tuition & Classes/Language/Shona",
//     "Services/Tuition & Classes/Language/Swahili",
//     "Services/Tuition & Classes/Language/Yoruba",
//     "Services/Tuition & Classes/Language/Igbo",
//     "Services/Tuition & Classes/Music",
//     "Services/Tuition & Classes/Music/Guitar Tuition",
//     "Services/Tuition & Classes/Music/Piano Tuition",
//     "Services/Tuition & Classes/Music/Singing Lessons",
//     "Services/Tuition & Classes/Music/Miscellaneous Music Lessons",
//     "Services/Tuition & Classes/Music/Drum Tuition",
//     "Services/Tuition & Classes/Music/Violin Tuition",
//     "Services/Tuition & Classes/Music/Saxophone Tuition",
//     "Services/Tuition & Classes/Miscellaneous Classes",
//     "Services/Tuition & Classes/Driving Lessons & Instructors",
//     "Services/Tuition & Classes/Arts & Crafts",
//     "Services/Tuition & Classes/IT & Computing",
//     "Services/Tuition & Classes/Construction",
//     "Services/Tuition & Classes/Business",
//     "Services/Tuition & Classes/Health & Fitness",
//     "Services/Health & Beauty",
//     "Services/Health & Beauty/Massages",
//     "Services/Health & Beauty/Hairdressing",
//     "Services/Health & Beauty/Beauty Treatments",
//     "Services/Health & Beauty/Personal Trainers",
//     "Services/Health & Beauty/Miscellaneous Health & Beauty Services",
//     "Services/Health & Beauty/Make Up Artists",
//     "Services/Health & Beauty/Alternative Therapies",
//     "Services/Health & Beauty/Nursing & Care",
//     "Services/Health & Beauty/Life Coaching",
//     "Services/Health & Beauty/Tattooing & Piercing",
//     "Services/Health & Beauty/Doctors & Clinics",
//     "Services/Health & Beauty/Chiropodists & Podiatrists",
//     "Services/Health & Beauty/Dentists",
//     "Services/Health & Beauty/Models & Actors",
//     "Services/Property & Maintenance",
//     "Services/Property & Maintenance/Cleaners",
//     "Services/Property & Maintenance/Cleaners/Domestic Cleaning",
//     "Services/Property & Maintenance/Cleaners/Carpet Cleaning",
//     "Services/Property & Maintenance/Cleaners/Commerical & Office Cleaning",
//     "Services/Property & Maintenance/Cleaners/Miscellaneous Cleaning",
//     "Services/Property & Maintenance/Cleaners/Window Cleaning",
//     "Services/Property & Maintenance/Property Maintenance Services",
//     "Services/Property & Maintenance/Miscellaneous Property & Maintenance Services",
//     "Services/Property & Maintenance/Housekeepers",
//     "Services/Property & Maintenance/Interior Designers",
//     "Services/Property & Maintenance/Drain & Pipe Cleaning",
//     "Services/Property & Maintenance/Satellite, Aerial & TV",
//     "Services/Property & Maintenance/Security Services",
//     "Services/Property & Maintenance/Security Services/Property",
//     "Services/Property & Maintenance/Security Services/Door",
//     "Services/Property & Maintenance/Estate Agents",
//     "Services/Property & Maintenance/Property Consultants",
//     "Services/Property & Maintenance/Letting Agents",
//     "Services/Property & Maintenance/Upholsterers",
//     "Services/Motoring",
//     "Services/Motoring/Vehicle Recovery Services",
//     "Services/Motoring/Car Servicing & Repair",
//     "Services/Motoring/Miscellaneous Motoring Services",
//     "Services/Motoring/Garage & Mechanic Services",
//     "Services/Motoring/Body Repair",
//     "Services/Motoring/Car Valeting",
//     "Services/Motoring/Car Breakers",
//     "Services/Motoring/Tyre Fitting",
//     "Services/Motoring/Car Wash",
//     "Services/Transport",
//     "Services/Transport/Car Hire",
//     "Services/Transport/Bus & Coach",
//     "Services/Transport/Van & Truck Hire",
//     "Services/Transport/Taxi",
//     "Services/Transport/Chauffeur & Limousine Hire",
//     "Services/Transport/Vehicle Hire",
//     "Services/Transport/Coach Hire",
//     "Services/Business & Office",
//     "Services/Business & Office/Miscellaneous Business & Office Services",
//     "Services/Business & Office/Accounting",
//     "Services/Business & Office/Accounting/Accountants",
//     "Services/Business & Office/Accounting/Tax",
//     "Services/Business & Office/Accounting/Bookkeeping",
//     "Services/Business & Office/Accounting/Miscellaneous Accounting",
//     "Services/Business & Office/Writing & Literature",
//     "Services/Business & Office/Writing & Literature/Proof Reading",
//     "Services/Business & Office/Writing & Literature/Creative Writing",
//     "Services/Business & Office/Writing & Literature/Copywriting",
//     "Services/Business & Office/Courier Services",
//     "Services/Business & Office/General Office Services",
//     "Services/Business & Office/Storage",
//     "Services/Business & Office/Marketing",
//     "Services/Business & Office/Shipping",
//     "Services/Business & Office/Health & Safety",
//     "Services/Business & Office/Interpreting & Translation",
//     "Services/Business & Office/Leaflet Distribution",
//     "Services/Business & Office/Secretarial Services",
//     "Services/Business & Office/Printing",
//     "Services/Business & Office/Recruitment",
//     "Services/Business & Office/Advertising Agencies",
//     "Services/Business & Office/Overseas Business",
//     "Services/Business & Office/Sign Makers",
//     "Services/Business & Office/Wholesale",
//     "Services/Business & Office/Shredding Services",
//     "Services/Entertainment",
//     "Services/Entertainment/DJ & Disco Hire",
//     "Services/Entertainment/Miscellaneous Entertainment Services",
//     "Services/Entertainment/Bands & Musicians",
//     "Services/Entertainment/Entertainers",
//     "Services/Entertainment/Function Rooms & Banqueting Facilities",
//     "Services/Entertainment/Catering",
//     "Services/Entertainment/Venues & Nightclubs",
//     "Services/Weddings",
//     "Services/Weddings/Photography & Film",
//     "Services/Weddings/Miscellaneous Wedding Services",
//     "Services/Weddings/Cars & Transportation",
//     "Services/Weddings/Catering & Services",
//     "Services/Weddings/Organisers & Planners",
//     "Services/Weddings/Marquee Hire",
//     "Services/Weddings/Entertainment",
//     "Services/Weddings/Florists",
//     "Services/Weddings/Wedding & Reception Venues",
//     "Services/Weddings/Hairdressers",
//     "Services/Computers & Telecoms",
//     "Services/Computers & Telecoms/Website Design",
//     "Services/Computers & Telecoms/Computer Repair",
//     "Services/Computers & Telecoms/Computer Support",
//     "Services/Computers & Telecoms/Computer Network",
//     "Services/Computers & Telecoms/Web Development",
//     "Services/Computers & Telecoms/Computer Services",
//     "Services/Computers & Telecoms/Software Application Development",
//     "Services/Computers & Telecoms/Telecom & Internet Service Providers",
//     "Services/Computers & Telecoms/Web Services",
//     "Services/Computers & Telecoms/Phone & Tablet Repair",
//     "Services/Computers & Telecoms/Miscellaneous Computer Services",
//     "Services/Pets",
//     "Services/Pets/Petsitters & Dogwalkers",
//     "Services/Pets/Grooming",
//     "Services/Pets/Training",
//     "Services/Pets/Vets",
//     "Services/Pets/Supplies",
//     "Services/Childcare",
//     "Services/Childcare/Babysitting",
//     "Services/Childcare/Nannies",
//     "Services/Childcare/Childminders",
//     "Services/Childcare/Au pairs",
//     "Services/Childcare/Miscellaneous Children Services",
//     "Services/Childcare/Parent Support",
//     "Services/Childcare/Children's Activities",
//     "Services/Food & Drink",
//     "Services/Food & Drink/Miscellaneous Food & Drink",
//     "Services/Food & Drink/Takeaways",
//     "Services/Food & Drink/Restaurants",
//     "Services/Food & Drink/Cafes",
//     "Services/Food & Drink/Bars & Pubs",
//     "Services/Food & Drink/Bakery",
//     "Services/Finance & Legal",
//     "Services/Finance & Legal/Financial Advice",
//     "Services/Finance & Legal/Legal Services",
//     "Services/Finance & Legal/Mortgage Brokers",
//     "Services/Finance & Legal/Visa & Immigration",
//     "Services/Finance & Legal/Money Transfer",
//     "Services/Finance & Legal/Solicitors & Conveyancing",
//     "Services/Clothing",
//     "Services/Clothing/Seamstress/Tailors",
//     "Services/Clothing/Dry Cleaning & Laundry",
//     "Services/Clothing/Embroidery",
//     "Services/Clothing/Stylists",
//     "Services/Goods Suppliers & Retailers",
//     "Services/Goods Suppliers & Retailers/Miscellaneous Goods Suppliers & Retailers",
//     "Services/Goods Suppliers & Retailers/Electrical",
//     "Services/Goods Suppliers & Retailers/Bike Shops",
//     "Services/Goods Suppliers & Retailers/Health Products",
//     "Services/Goods Suppliers & Retailers/Clothes Stores",
//     "Services/Goods Suppliers & Retailers/Jewellers",
//     "Services/Goods Suppliers & Retailers/Mobile Phone",
//     "Services/Goods Suppliers & Retailers/Supermarkets",
//     "Services/Travel & Tourism",
//     "Services/Travel & Tourism/Caravan Hire",
//     "Services/Travel & Tourism/Travel Agents",
//     "Services/Travel & Tourism/Rest of World",
//     "Services/Travel & Tourism/Hostel & Hotels",
//     "Community/Artists & Theatres",
//     "Community/Classes",
//     "Community/Events",
//     "Community/Groups & Associations",
//     "Community/Lost & Found Stuff",
//     "Community/Music, Bands & Musicians",
//     "Community/Rideshare & Car Pooling",
//     "Community/Skills & Language Swap",
//     "Community/Sports Teams",
//     "Community/Travel & Travel Partners",
//     "Pets/Pets for Sale",
//     "Pets/Pets for Sale/Dogs",
//     "Pets/Pets for Sale/Cats",
//     "Pets/Pets for Sale/Small Furries",
//     "Pets/Pets for Sale/Birds",
//     "Pets/Pets for Sale/Fish",
//     "Pets/Pets for Sale/Exotics",
//     "Pets/Pets for Sale/Horses & Ponies",
//     "Pets/Equipment & Accessories",
//     "Pets/Missing & Found Pets",
//     "Property/To Rent",
//     "Property/Commercial",
//     "Property/To Share",
//     "Property/To Share/To Rent",
//     "Property/To Share/For Sale",
//     "Property/Parking & Garage",
//     "Property/For Sale",
//     "Property/Property Wanted",
//     "Property/To Swap",
//     "Property/Holiday Rentals",
//     "Property/Holiday Rentals/Flat",
//     "Property/Holiday Rentals/House",
//     "Property/Holiday Rentals/Miscellaneous",
//     "Property/International",
//     "Cars And Vehicles",
//     "Cars And Vehicles/Cars",
//     "Cars And Vehicles/Motorbikes & Scooters",
//     "Cars And Vehicles/Vans",
//     "Cars And Vehicles/Campervans & Motorhomes",
//     "Cars And Vehicles/Caravans",
//     "Cars And Vehicles/Trucks",
//     "Cars And Vehicles/Plant & Tractors",
//     "Cars And Vehicles/Other Vehicles",
//     "Cars And Vehicles/Parts/Car Parts",
//     "Cars And Vehicles/Parts/Campervan & Caravan Parts",
//     "Cars And Vehicles/Parts/Motorbike & Scooter Parts",
//     "Cars And Vehicles/Parts/Van Parts",
//     "Cars And Vehicles/Parts/Plant & Tractor Parts",
//     "Cars And Vehicles/Parts/Truck Parts",
//     "Cars And Vehicles/Accessories/Other Accessories",
//     "Cars And Vehicles/Accessories/Wheel Rims & Tyres",
//     "Cars And Vehicles/Accessories/Clothes, Helmets & Boots",
//     "Cars And Vehicles/Accessories/Car Tuning & Styling",
//     "Cars And Vehicles/Accessories/In-Car Audio & GPS",
//     "Cars And Vehicles/Accessories/Motorbike Accessories & Styling"
// ]

export const categoriesArray = processCategories(categories)
// console.log('CATEGORIES_ARRAY',categoriesArray.length);
